### ISSUE TITLE
How to replace files that are not in the pak01-dir.vpk directory

### ISSUE THREAD

**Issue by tsxlts** [AspectUnk/s2-swapping#2]
I want to replace files that are not in the pak01-dir.vpk directory, for example, I need to replace "game\csgo\maps\ui\inspect_gloves. vpk". How should I proceed.

**Comment by AspectUnk** [comment]
Hi, I haven't done this myself, but the only thing I know is that the exported files from the source2 viewer are somehow recompiled after modifications using the tools from Half-Life: Alyx

**Comment by AspectUnk** [comment]
iirc it doesn't matter to us which vpk the game loads, we are only interested in the relative path that you can see in the source2 viewer, so you need to perform all the same
