### ISSUE TITLE
Спасибо тебе

### ISSUE THREAD

**Issue by Blackfox2012** [AspectUnk/s2-swapping#3]
дружок

**Comment by Blackfox2012** [comment]
поменял некоторые параметры панорамы в новой игре от валв, чувствую себя богом жизни, дай бог тебе здоровья и чтоб вакбан мне не прилетел (в онлайн не суюсь конечно)

**Comment by Blackfox2012** [comment]
кстати ниче не рекомпилил, уже компиленную шнягу редачил вытащенную из впк. там очень важно чтобы заместо символа оригинала стоял другой символ, например: width 100px значит надо width 000px писать, если символов меньше будет то будут крашики

**Comment by AspectUnk** [comment]
Приятно знать, что это кому то помогло 🫠
